name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: .
    
      - name: DB up
        run: npm run db:up

      - name: Build db
        run: npm run build -w @labatory/db

      - name: Build
        run: npm run web:build

      - name: DB down
        run: npm run db:down
  